{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "19793b3e",
   "metadata": {},
   "source": [
    "### This file is for addding a column of time in the energy file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "753ed711",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-08-30 20:41:29.555762: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-08-30 20:41:29.555787: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import regex as re\n",
    "import sys, os\n",
    "import time\n",
    "import ast\n",
    "import math\n",
    "from statistics import mean\n",
    "from ast import literal_eval\n",
    "import numpy as np\n",
    "import csv\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.datasets import load_digits\n",
    "from sklearn.model_selection import train_test_split\n",
    "from imblearn.over_sampling import SMOTE\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn import metrics\n",
    "import matplotlib.pyplot as plt\n",
    "from pandas.api.types import is_string_dtype\n",
    "from pandas.api.types import is_numeric_dtype\n",
    "from statistics import mean, median\n",
    "from sklearn.tree import DecisionTreeClassifier \n",
    "from collections import Counter\n",
    "# neural network\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from keras.preprocessing.sequence import pad_sequences\n",
    "import tensorflow as tf\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense, Dropout, Activation\n",
    "from keras.layers import Embedding\n",
    "from keras.layers import LSTM\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97602cc4",
   "metadata": {},
   "source": [
    "### Mirei attack dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "13fffba1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pandas import DataFrame\n",
    "from pandas import concat\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):\n",
    "    \"\"\"\n",
    "    Frame a time series as a supervised learning dataset.\n",
    "    Arguments:\n",
    "        data: Sequence of observations as a list or NumPy array.\n",
    "        n_in: Number of lag observations as input (X).\n",
    "        n_out: Number of observations as output (y).\n",
    "        dropnan: Boolean whether or not to drop rows with NaN values.\n",
    "    Returns:\n",
    "        Pandas DataFrame of series framed for supervised learning.\n",
    "    \"\"\"\n",
    "    n_vars = 1 if type(data) is list else data.shape[1]\n",
    "    df = DataFrame(data)\n",
    "#     print(df)\n",
    "    cols, names = list(), list()\n",
    "    # input sequence (t-n, ... t-1)\n",
    "    for i in range(n_in, 0, -1):\n",
    "        cols.append(df.shift(i))\n",
    "        names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]\n",
    "    # forecast sequence (t, t+1, ... t+n)\n",
    "    for i in range(0, n_out):\n",
    "        cols.append(df.shift(-i))\n",
    "        if i == 0:\n",
    "            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]\n",
    "        else:\n",
    "            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]\n",
    "    # put it all together\n",
    "    agg = concat(cols, axis=1)\n",
    "    agg.columns = names\n",
    "    # drop rows with NaN values\n",
    "    if dropnan:\n",
    "        agg.dropna(inplace=True)\n",
    "    return agg\n",
    "\n",
    "\n",
    "\n",
    "def get_pre_rec(model, X_train, X_test, y_train, y_test):\n",
    "    model.fit(X_train, y_train)\n",
    "    y_pred = model.predict(X_test)\n",
    "#     print(y_pred)\n",
    "#     print(y_test)\n",
    "    pre=precision_score(y_test, y_pred, average='weighted')\n",
    "    rec=recall_score(y_test, y_pred, average='weighted')\n",
    "    fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred, pos_label=1)\n",
    "    #print (fpr, tpr, thresholds)\n",
    "    auc=metrics.auc(fpr, tpr)\n",
    "    return pre, rec, auc\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c1b49ce1",
   "metadata": {},
   "source": [
    "## Make energy to timestamp dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "d8a7cddf",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Actual attack is UFOnet\n",
      "archer\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/UFOnet/archer-UFOnet.csv\n",
      "writing\n",
      "cctv\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/UFOnet/cctv-UFOnet.csv\n",
      "writing\n",
      "indoor\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/UFOnet/indoor-UFOnet.csv\n",
      "writing\n",
      "Actual attack is RouterSploit\n",
      "wr940n\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/wr940n-RouterSploit.csv\n",
      "writing\n",
      "archer\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/archer-RouterSploit.csv\n",
      "writing\n",
      "camera\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/camera-RouterSploit.csv\n",
      "writing\n",
      "cctv\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/cctv-RouterSploit.csv\n",
      "writing\n",
      "indoor\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/indoor-RouterSploit.csv\n",
      "writing\n",
      "phillips\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/RouterSploit/phillips-RouterSploit.csv\n",
      "writing\n",
      "Actual attack is Mirai\n",
      "wr940n\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/wr940n-Mirai.csv\n",
      "writing\n",
      "archer\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/archer-Mirai.csv\n",
      "writing\n",
      "camera\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/camera-Mirai.csv\n",
      "writing\n",
      "cctv\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/cctv-Mirai.csv\n",
      "writing\n",
      "indoor\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/indoor-Mirai.csv\n",
      "writing\n",
      "phillips\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Mirai/phillips-Mirai.csv\n",
      "writing\n",
      "Actual attack is Normal\n",
      "wr940n\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/wr940n-Normal.csv\n",
      "writing\n",
      "archer\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/archer-Normal.csv\n",
      "writing\n",
      "camera\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/camera-Normal.csv\n",
      "writing\n",
      "cctv\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/cctv-Normal.csv\n",
      "writing\n",
      "indoor\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/indoor-Normal.csv\n",
      "writing\n",
      "phillips\n",
      "/home/amine/Documents/CRIM_Project/Energy-network/Normal/phillips-Normal.csv\n",
      "writing\n"
     ]
    }
   ],
   "source": [
    "\n",
    "attacks = [\"UFOnet\",\"RouterSploit\", \"Mirai\",  \"Normal\"]\n",
    "\n",
    "\n",
    "\n",
    "for attack in attacks:\n",
    "    iot_devices = [\"wr940n\", \"archer\", \"camera\", \"cctv\", \"indoor\", \"phillips\"]\n",
    "    print(\"Actual attack is\", attack)\n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/Energy-network/\"+attack+\"/\"\n",
    "    \n",
    "    if attack == \"UFOnet\":\n",
    "        iot_devices = [\"archer\", \"cctv\", \"indoor\"]\n",
    "    \n",
    "    dfObj = pd.DataFrame()\n",
    "\n",
    "    \n",
    "\n",
    "    for i, target in enumerate(iot_devices):\n",
    "        output = \"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"+target+\"-\"+attack+\".csv\"\n",
    "        print(target)\n",
    "        dataset_file =  dataset_folder+target+\"-\"+attack+\".csv\"\n",
    "\n",
    "        if os.path.isfile(dataset_file):\n",
    "            print(dataset_file)\n",
    "            dataset = pd.read_csv(dataset_file, delimiter=',')\n",
    "            \n",
    "            \n",
    "            for index, line in dataset.iterrows():\n",
    "                \n",
    "                val = int(len(ast.literal_eval(line['protocol'])))\n",
    "                dataset.loc[index,'packet'] = val\n",
    "                unique_sour = len(set(ast.literal_eval(line['source'])))\n",
    "                unique_dest = len(set(ast.literal_eval(line['destination'])))\n",
    "                list_length = list(ast.literal_eval(line['length']))\n",
    "                if(list_length):\n",
    "                    list_length.sort()\n",
    "                    max_len = int(max (list_length))\n",
    "                    min_len = int(min (list_length))\n",
    "                    mean_len = mean (list_length)\n",
    "                    mid = len(list_length) // 2\n",
    "                    median_len = (list_length[mid] + list_length[~mid]) / 2\n",
    "                dataset.loc[index,'unique_sour'] = unique_sour\n",
    "                dataset.loc[index,'unique_dest'] = unique_dest\n",
    "                dataset.loc[index,'median_len'] = median_len\n",
    "                dataset.loc[index,'mean_len'] = mean_len\n",
    "                dataset.loc[index,'max_len'] = max_len\n",
    "                dataset.loc[index,'min_len'] = min_len\n",
    "                \n",
    "            dataset = dataset.drop(columns=['source', 'destination', 'info', 'length', 'timestamp', 'time'])\n",
    "#             print(dataset)\n",
    "            cols = dataset.columns\n",
    "\n",
    "            dataset_series = series_to_supervised(dataset, 2)\n",
    "\n",
    "            dataset_series [\"device\"] = i\n",
    "            \n",
    "            \n",
    "#         dfObj = dfObj.append(dataset_series) \n",
    "        \n",
    "            for count, c in enumerate(cols):\n",
    "                dataset_series.columns = dataset_series.columns.str.replace(\"var\"+str(count+1), c)\n",
    "#             print(dataset_series.columns)\n",
    "            print(\"writing\")\n",
    "            dataset_series.to_csv(output, encoding='utf-8', index=False)\n",
    "\n",
    "            \n",
    "            \n",
    "\n",
    "        \n",
    "  "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9e49860",
   "metadata": {},
   "source": [
    "## Mixte each attack with the normal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "59f7ed9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Actual attack is Mirai\n",
      "Actual attack is RouterSploit\n",
      "Actual attack is UFOnet\n",
      "Actual attack is Normal\n"
     ]
    }
   ],
   "source": [
    "attacks = [\"Mirai\", \"RouterSploit\", \"UFOnet\", \"Normal\"]\n",
    "\n",
    "\n",
    "\n",
    "for attack in attacks:\n",
    "    \n",
    "    iot_devices = [\"wr940n\", \"archer\", \"camera\", \"cctv\", \"indoor\", \"phillips\"]\n",
    "    print(\"Actual attack is\", attack)\n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/Energy-network/\"+attack+\"/\"\n",
    "    \n",
    "    if attack == \"UFOnet\":\n",
    "        iot_devices = [\"archer\", \"cctv\", \"indoor\"]\n",
    "    \n",
    "    dfObj = pd.DataFrame()\n",
    "\n",
    "    for i, target in enumerate(iot_devices):\n",
    "        dataset_file = \"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"+target+\"-\"+attack+\".csv\"\n",
    "        \n",
    "        \n",
    "        dataset = pd.read_csv(dataset_file, delimiter=',')\n",
    "        \n",
    "        \n",
    "        dfObj = dfObj.append(dataset) \n",
    "        \n",
    "#     print(dfObj)\n",
    "    \n",
    "    \n",
    "    dfObj.to_csv(\"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"+attack+\"-all.csv\", encoding='utf-8', index=False)\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "a4e6ac68",
   "metadata": {},
   "outputs": [],
   "source": [
    "attacks = [\"Mirai\", \"RouterSploit\", \"UFOnet\"]\n",
    "\n",
    "\n",
    "\n",
    "for attack in attacks:    \n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"\n",
    "    mirei_input_folder = dataset_folder+attack+\"-all.csv\"\n",
    "    \n",
    "    mirei_output_folder = dataset_folder+\"pre_ml-\"+attack+\".csv\"\n",
    "\n",
    "    dataset_attack = pd.read_csv(mirei_input_folder, delimiter=',')\n",
    "    dataset_normal = pd.read_csv(\"/home/amine/Documents/CRIM_Project/timeseries_energy_network/Normal/Normal-all.csv\", delimiter=',')\n",
    "\n",
    "    dataset_attack['target'] = 1\n",
    "    dataset_normal['target'] = 0\n",
    "    merged_data = pd.concat([dataset_attack,dataset_normal], axis=0)\n",
    "    \n",
    "    \n",
    "    merged_data.to_csv(mirei_output_folder, index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "04e1fd1b",
   "metadata": {},
   "source": [
    "### Dummies for protocol variables"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "b6676f98",
   "metadata": {},
   "outputs": [],
   "source": [
    "attacks = [\"Mirai\", \"RouterSploit\", \"UFOnet\"]\n",
    "from collections import Counter\n",
    "\n",
    "\n",
    "for attack in attacks:  \n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"\n",
    "    mirei_input_folder = dataset_folder+\"pre_ml-\"+attack+\".csv\"\n",
    "    mirei_output_folder = dataset_folder+\"pre_ml_dummies-\"+attack+\".csv\"\n",
    "    dataset = pd.read_csv(mirei_input_folder, delimiter=',')\n",
    "    \n",
    "    \n",
    "    columns_dum = ['protocol(t-2)', 'protocol(t-1)', 'protocol(t)']\n",
    "    \n",
    "    for col in columns_dum:\n",
    "        bridge_types = []\n",
    "        for index, line in dataset.iterrows():\n",
    "            \n",
    "            val = list(set(ast.literal_eval(line[col])))\n",
    "            bridge_types.extend(val)\n",
    "            bridge_types = list(set(bridge_types))\n",
    "        \n",
    "                \n",
    "        for col_bridge in bridge_types:\n",
    "            dataset[col+'_'+col_bridge] = 0 \n",
    "            \n",
    "        for index, line in dataset.iterrows():\n",
    "            val = list(set(ast.literal_eval(line[col])))\n",
    "            \n",
    "            \n",
    "            occurrences = dict(Counter(val))\n",
    "            \n",
    "            for pro, occ in occurrences.items():\n",
    "                \n",
    "                dataset.loc[index, col+'_'+pro] = occ\n",
    "        \n",
    "        del dataset[col]\n",
    "\n",
    "            \n",
    "            \n",
    "#         print(dataset)\n",
    "    dataset.to_csv(mirei_output_folder, index=False)\n",
    "        "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ec1e3396",
   "metadata": {},
   "source": [
    "## Apply ML algrithms (random forest, logictic regression, decision tree)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3d83fc0b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "random forest 98.16 98.16 97.51\n",
      "logistic regression78.30 64.96 71.13\n",
      "decision tree 98.15 98.15 97.49\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "random forest 97.97 97.95 98.00\n",
      "logistic regression55.98 56.25 55.57\n",
      "decision tree 97.48 97.47 97.50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/home/amine/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "random forest 99.93 99.93 99.91\n",
      "logistic regression84.61 64.88 65.69\n",
      "decision tree 99.91 99.91 99.85\n"
     ]
    }
   ],
   "source": [
    "attacks = [\"Mirai\", \"RouterSploit\", \"UFOnet\"]\n",
    "\n",
    "\n",
    "\n",
    "for attack in attacks:\n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/timeseries_energy_network/\"+attack+\"/\"\n",
    "    input_folder = dataset_folder+\"pre_ml_dummies-\"+attack+\".csv\"\n",
    "    dataset = pd.read_csv(input_folder, delimiter=',')\n",
    "    \n",
    "    target='target'\n",
    "\n",
    "#     features = list(dataset.columns)\n",
    "#     print(list(dataset.columns))\n",
    "    dataset = dataset[~dataset[target].isnull()]\n",
    "    dataset=dataset.reset_index(drop=True)\n",
    "    \n",
    "    \n",
    "    y = dataset[target].astype(int)\n",
    "#     print(y.value_counts())\n",
    "    features = list(dataset.columns)\n",
    "    features.remove(target)\n",
    "#     energy_features = [\"energy(t)\", \"energy(t-1)\", \"energy(t-2)\"]\n",
    "#     for e in energy_features:\n",
    "#         features.remove(e)\n",
    "    x = dataset[features]\n",
    "    \n",
    "    folds = StratifiedKFold(n_splits=10, shuffle=True)\n",
    "    pre_rf = []\n",
    "    pre1_rf = []\n",
    "    pre2_rf = []\n",
    "    rec_rf = []\n",
    "    rec1_rf = []\n",
    "    rec2_rf = []\n",
    "    auc_rf = []\n",
    "    auc1_rf = []\n",
    "    auc2_rf = []\n",
    "    for train_index, test_index in folds.split(x,y):\n",
    "        x_train=x.iloc[train_index]\n",
    "        x_test=x.iloc[test_index]\n",
    "        y_train=y.iloc[train_index]\n",
    "        y_test =  y.iloc[test_index]\n",
    "        sm = SMOTE(random_state=42, sampling_strategy='auto')\n",
    "        x_train, y_train = sm.fit_resample(x_train, y_train)\n",
    "\n",
    "\n",
    "\n",
    "        pre, rec, auc = get_pre_rec(RandomForestClassifier(), x_train, x_test, y_train, y_test)\n",
    "        pre1, rec1, auc1 = get_pre_rec(LogisticRegression(), x_train, x_test, y_train, y_test)\n",
    "        pre2, rec2, auc2 = get_pre_rec(DecisionTreeClassifier(), x_train, x_test, y_train, y_test)\n",
    "        pre_rf.append (pre)\n",
    "        rec_rf.append (rec)\n",
    "        auc_rf.append (auc)\n",
    "        pre1_rf.append (pre1)\n",
    "        rec1_rf.append (rec1)\n",
    "        auc1_rf.append (auc1)\n",
    "        pre2_rf.append (pre2)\n",
    "        rec2_rf.append (rec2)\n",
    "        auc2_rf.append (auc2)\n",
    "\n",
    "\n",
    "    print (\"random forest {:.2f}\".format(median(pre_rf)*100), \"{:.2f}\".format(median(rec_rf)*100), \"{:.2f}\".format(median(auc_rf)*100) )\n",
    "    print (\"logistic regression{:.2f}\".format(median(pre1_rf)*100), \"{:.2f}\".format(median(rec1_rf)*100), \"{:.2f}\".format(median(auc1_rf)*100))\n",
    "    print (\"decision tree {:.2f}\".format(median(pre2_rf)*100), \"{:.2f}\".format(median(rec2_rf)*100), \"{:.2f}\".format(median(auc2_rf)*100))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0b2a57f4",
   "metadata": {},
   "source": [
    "## Neural Network"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee3f14b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mirai\n",
      "Epoch 1/5\n",
      "41525/41525 - 20s - loss: 0.5573 - recall: 0.9956 - precision: 0.7464\n",
      "Epoch 2/5\n",
      "41525/41525 - 19s - loss: 0.5133 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 3/5\n",
      "41525/41525 - 20s - loss: 0.4573 - recall: 0.9982 - precision: 0.8017\n",
      "Epoch 4/5\n",
      "41525/41525 - 20s - loss: 0.4164 - recall: 0.9956 - precision: 0.8254\n",
      "Epoch 5/5\n",
      "41525/41525 - 20s - loss: 0.4019 - recall: 0.9918 - precision: 0.8265\n",
      "4614/4614 - 2s - loss: 0.3936 - recall: 0.9991 - precision: 0.8290\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 21s - loss: 0.5562 - recall: 0.9962 - precision: 0.7477\n",
      "Epoch 2/5\n",
      "41525/41525 - 22s - loss: 0.5255 - recall: 0.9930 - precision: 0.7575\n",
      "Epoch 3/5\n",
      "41525/41525 - 21s - loss: 0.5178 - recall: 0.9835 - precision: 0.7567\n",
      "Epoch 4/5\n",
      "41525/41525 - 21s - loss: 0.5156 - recall: 0.9790 - precision: 0.7563\n",
      "Epoch 5/5\n",
      "41525/41525 - 21s - loss: 0.5139 - recall: 0.9784 - precision: 0.7559\n",
      "4614/4614 - 2s - loss: 0.5174 - recall: 0.9988 - precision: 0.7568\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 21s - loss: 0.5569 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 2/5\n",
      "41525/41525 - 20s - loss: 0.5158 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 3/5\n",
      "41525/41525 - 20s - loss: 0.5079 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 4/5\n",
      "41525/41525 - 20s - loss: 0.5070 - recall: 1.0000 - precision: 0.7469\n",
      "Epoch 5/5\n",
      "41525/41525 - 20s - loss: 0.5062 - recall: 1.0000 - precision: 0.7472\n",
      "4614/4614 - 2s - loss: 0.4992 - recall: 1.0000 - precision: 0.7497\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 22s - loss: 0.5266 - recall: 0.9929 - precision: 0.7723\n",
      "Epoch 2/5\n",
      "41525/41525 - 21s - loss: 0.4935 - recall: 0.9985 - precision: 0.7901\n",
      "Epoch 3/5\n",
      "41525/41525 - 22s - loss: 0.4930 - recall: 0.9985 - precision: 0.7902\n",
      "Epoch 4/5\n",
      "41525/41525 - 23s - loss: 0.4930 - recall: 0.9985 - precision: 0.7904\n",
      "Epoch 5/5\n",
      "41525/41525 - 21s - loss: 0.4930 - recall: 0.9985 - precision: 0.7904\n",
      "4614/4614 - 2s - loss: 0.4864 - recall: 0.9991 - precision: 0.7911\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 21s - loss: 0.5368 - recall: 0.9947 - precision: 0.7485\n",
      "Epoch 2/5\n",
      "41525/41525 - 20s - loss: 0.4617 - recall: 0.9987 - precision: 0.7764\n",
      "Epoch 3/5\n",
      "41525/41525 - 20s - loss: 0.4178 - recall: 0.9960 - precision: 0.8213\n",
      "Epoch 4/5\n",
      "41525/41525 - 21s - loss: 0.3799 - recall: 0.9955 - precision: 0.8439\n",
      "Epoch 5/5\n",
      "41525/41525 - 21s - loss: 0.3484 - recall: 0.9948 - precision: 0.8598\n",
      "4614/4614 - 2s - loss: 0.3290 - recall: 0.9968 - precision: 0.8704\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 21s - loss: 0.5260 - recall: 0.9996 - precision: 0.7546\n",
      "Epoch 2/5\n",
      "41525/41525 - 21s - loss: 0.4524 - recall: 0.9964 - precision: 0.8121\n",
      "Epoch 3/5\n",
      "41525/41525 - 21s - loss: 0.4074 - recall: 0.9907 - precision: 0.8317\n",
      "Epoch 4/5\n",
      "41525/41525 - 20s - loss: 0.3980 - recall: 0.9883 - precision: 0.8290\n",
      "Epoch 5/5\n",
      "41525/41525 - 20s - loss: 0.3939 - recall: 0.9866 - precision: 0.8266\n",
      "4614/4614 - 2s - loss: 0.4162 - recall: 0.8418 - precision: 0.8132\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 21s - loss: 0.4739 - recall: 0.9957 - precision: 0.7899\n",
      "Epoch 2/5\n",
      "41525/41525 - 25s - loss: 0.3418 - recall: 0.9982 - precision: 0.8440\n",
      "Epoch 3/5\n",
      "41525/41525 - 22s - loss: 0.2978 - recall: 0.9974 - precision: 0.8629\n",
      "Epoch 4/5\n",
      "41525/41525 - 22s - loss: 0.2843 - recall: 0.9965 - precision: 0.8650\n",
      "Epoch 5/5\n",
      "41525/41525 - 25s - loss: 0.2788 - recall: 0.9961 - precision: 0.8678\n",
      "4614/4614 - 3s - loss: 0.2937 - recall: 0.9965 - precision: 0.8544\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "41525/41525 - 25s - loss: 0.5558 - recall: 0.9999 - precision: 0.7465\n",
      "Epoch 2/5\n",
      "41525/41525 - 33s - loss: 0.5149 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 3/5\n",
      "41525/41525 - 32s - loss: 0.5067 - recall: 1.0000 - precision: 0.7465\n",
      "Epoch 4/5\n",
      "41525/41525 - 31s - loss: 0.5062 - recall: 1.0000 - precision: 0.7468\n",
      "Epoch 5/5\n",
      "41525/41525 - 30s - loss: 0.5054 - recall: 1.0000 - precision: 0.7503\n",
      "4614/4614 - 3s - loss: 0.5029 - recall: 1.0000 - precision: 0.7464\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41525/41525 - 32s - loss: 0.5201 - recall: 0.9992 - precision: 0.7603\n",
      "Epoch 2/5\n",
      "41525/41525 - 31s - loss: 0.4281 - recall: 0.9952 - precision: 0.8215\n",
      "Epoch 3/5\n",
      "41525/41525 - 31s - loss: 0.4014 - recall: 0.9857 - precision: 0.8282\n",
      "Epoch 4/5\n",
      "41525/41525 - 41s - loss: 0.3959 - recall: 0.9824 - precision: 0.8272\n",
      "Epoch 5/5\n",
      "41525/41525 - 41s - loss: 0.3937 - recall: 0.9792 - precision: 0.8265\n",
      "4614/4614 - 4s - loss: 0.3980 - recall: 0.9983 - precision: 0.8199\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41526/41526 - 44s - loss: 0.5273 - recall: 0.9877 - precision: 0.7717\n",
      "Epoch 2/5\n",
      "41526/41526 - 43s - loss: 0.4557 - recall: 0.9986 - precision: 0.7900\n",
      "Epoch 3/5\n",
      "41526/41526 - 29s - loss: 0.4308 - recall: 0.9981 - precision: 0.7993\n",
      "Epoch 4/5\n",
      "41526/41526 - 27s - loss: 0.4036 - recall: 0.9975 - precision: 0.8338\n",
      "Epoch 5/5\n",
      "41526/41526 - 36s - loss: 0.3896 - recall: 0.9974 - precision: 0.8353\n",
      "4613/4613 - 3s - loss: 0.3853 - recall: 0.9974 - precision: 0.8378\n",
      "Baseline: nan% (nan%)\n",
      "RouterSploit\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19343/19343 - 15s - loss: 0.6852 - recall: 0.2672 - precision: 0.5312\n",
      "Epoch 2/5\n",
      "19343/19343 - 15s - loss: 0.6786 - recall: 0.2672 - precision: 0.5449\n",
      "Epoch 3/5\n",
      "19343/19343 - 12s - loss: 0.6739 - recall: 0.3000 - precision: 0.5611\n",
      "Epoch 4/5\n",
      "19343/19343 - 10s - loss: 0.6668 - recall: 0.3314 - precision: 0.5909\n",
      "Epoch 5/5\n",
      "19343/19343 - 13s - loss: 0.6562 - recall: 0.3836 - precision: 0.6294\n",
      "2150/2150 - 2s - loss: 0.6517 - recall: 0.6469 - precision: 0.5975\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "19343/19343 - 15s - loss: 0.6883 - recall: 0.1881 - precision: 0.5100\n",
      "Epoch 2/5\n",
      "19343/19343 - 14s - loss: 0.6833 - recall: 0.2353 - precision: 0.5191\n",
      "Epoch 3/5\n",
      "19343/19343 - 14s - loss: 0.6783 - recall: 0.2947 - precision: 0.5717\n",
      "Epoch 4/5\n",
      "19343/19343 - 14s - loss: 0.6703 - recall: 0.3504 - precision: 0.6040\n",
      "Epoch 5/5\n",
      "19343/19343 - 11s - loss: 0.6605 - recall: 0.3924 - precision: 0.6029\n",
      "2150/2150 - 1s - loss: 0.6532 - recall: 0.3918 - precision: 0.9014\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19343/19343 - 11s - loss: 0.6866 - recall: 0.2079 - precision: 0.5023\n",
      "Epoch 2/5\n",
      "19343/19343 - 10s - loss: 0.6807 - recall: 0.2775 - precision: 0.5294\n",
      "Epoch 3/5\n",
      "19343/19343 - 10s - loss: 0.6743 - recall: 0.2820 - precision: 0.5225\n",
      "Epoch 4/5\n",
      "19343/19343 - 10s - loss: 0.6728 - recall: 0.2890 - precision: 0.5242\n",
      "Epoch 5/5\n",
      "19343/19343 - 10s - loss: 0.6722 - recall: 0.2916 - precision: 0.5212\n",
      "2150/2150 - 1s - loss: 0.6704 - recall: 0.2837 - precision: 0.4696\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 13s - loss: 0.6757 - recall: 0.1804 - precision: 0.5486\n",
      "Epoch 2/5\n",
      "19344/19344 - 12s - loss: 0.6616 - recall: 0.6430 - precision: 0.5431\n",
      "Epoch 3/5\n",
      "19344/19344 - 10s - loss: 0.6581 - recall: 0.6587 - precision: 0.5482\n",
      "Epoch 4/5\n",
      "19344/19344 - 11s - loss: 0.6518 - recall: 0.6541 - precision: 0.5592\n",
      "Epoch 5/5\n",
      "19344/19344 - 10s - loss: 0.5951 - recall: 0.6611 - precision: 0.6422\n",
      "2149/2149 - 1s - loss: 0.5607 - recall: 0.4051 - precision: 0.8921\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 10s - loss: 0.6829 - recall: 0.2579 - precision: 0.5261\n",
      "Epoch 2/5\n",
      "19344/19344 - 10s - loss: 0.6776 - recall: 0.3525 - precision: 0.5781\n",
      "Epoch 3/5\n",
      "19344/19344 - 13s - loss: 0.6724 - recall: 0.4142 - precision: 0.5947\n",
      "Epoch 4/5\n",
      "19344/19344 - 14s - loss: 0.6617 - recall: 0.4568 - precision: 0.6202\n",
      "Epoch 5/5\n",
      "19344/19344 - 17s - loss: 0.6438 - recall: 0.5359 - precision: 0.6224\n",
      "2149/2149 - 2s - loss: 0.6325 - recall: 0.5408 - precision: 0.5962\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "19344/19344 - 21s - loss: 0.6823 - recall: 0.2659 - precision: 0.4842\n",
      "Epoch 2/5\n",
      "19344/19344 - 15s - loss: 0.6717 - recall: 0.3222 - precision: 0.5084\n",
      "Epoch 3/5\n",
      "19344/19344 - 14s - loss: 0.6650 - recall: 0.3130 - precision: 0.5266\n",
      "Epoch 4/5\n",
      "19344/19344 - 15s - loss: 0.6509 - recall: 0.3227 - precision: 0.5406\n",
      "Epoch 5/5\n",
      "19344/19344 - 15s - loss: 0.6047 - recall: 0.4696 - precision: 0.6181\n",
      "2149/2149 - 1s - loss: 0.5727 - recall: 0.7847 - precision: 0.6934\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 13s - loss: 0.6732 - recall: 0.3080 - precision: 0.5651\n",
      "Epoch 2/5\n",
      "19344/19344 - 13s - loss: 0.6268 - recall: 0.5023 - precision: 0.6121\n",
      "Epoch 3/5\n",
      "19344/19344 - 13s - loss: 0.5995 - recall: 0.6136 - precision: 0.6200\n",
      "Epoch 4/5\n",
      "19344/19344 - 13s - loss: 0.5838 - recall: 0.6755 - precision: 0.6633\n",
      "Epoch 5/5\n",
      "19344/19344 - 13s - loss: 0.5782 - recall: 0.6982 - precision: 0.6783\n",
      "2149/2149 - 2s - loss: 0.5846 - recall: 0.7265 - precision: 0.6813\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 15s - loss: 0.6840 - recall: 0.2766 - precision: 0.5141\n",
      "Epoch 2/5\n",
      "19344/19344 - 15s - loss: 0.6627 - recall: 0.2920 - precision: 0.5336\n",
      "Epoch 3/5\n",
      "19344/19344 - 15s - loss: 0.6219 - recall: 0.5726 - precision: 0.7185\n",
      "Epoch 4/5\n",
      "19344/19344 - 15s - loss: 0.5726 - recall: 0.7599 - precision: 0.7530\n",
      "Epoch 5/5\n",
      "19344/19344 - 15s - loss: 0.5293 - recall: 0.8423 - precision: 0.8339\n",
      "2149/2149 - 2s - loss: 0.5317 - recall: 0.9031 - precision: 0.7207\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 17s - loss: 0.6841 - recall: 0.2636 - precision: 0.5312\n",
      "Epoch 2/5\n",
      "19344/19344 - 12s - loss: 0.6733 - recall: 0.2973 - precision: 0.5042\n",
      "Epoch 3/5\n",
      "19344/19344 - 12s - loss: 0.6721 - recall: 0.2967 - precision: 0.4817\n",
      "Epoch 4/5\n",
      "19344/19344 - 12s - loss: 0.6682 - recall: 0.3217 - precision: 0.4860\n",
      "Epoch 5/5\n",
      "19344/19344 - 13s - loss: 0.6656 - recall: 0.3105 - precision: 0.4950\n",
      "2149/2149 - 2s - loss: 0.6681 - recall: 0.2492 - precision: 0.4890\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19344/19344 - 14s - loss: 0.6839 - recall: 0.1950 - precision: 0.5291\n",
      "Epoch 2/5\n",
      "19344/19344 - 13s - loss: 0.6772 - recall: 0.2918 - precision: 0.5304\n",
      "Epoch 3/5\n",
      "19344/19344 - 13s - loss: 0.6734 - recall: 0.3787 - precision: 0.5760\n",
      "Epoch 4/5\n",
      "19344/19344 - 12s - loss: 0.6690 - recall: 0.4106 - precision: 0.5959\n",
      "Epoch 5/5\n",
      "19344/19344 - 12s - loss: 0.6620 - recall: 0.4491 - precision: 0.6136\n",
      "2149/2149 - 1s - loss: 0.6588 - recall: 0.7191 - precision: 0.6400\n",
      "Baseline: nan% (nan%)\n",
      "UFOnet\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "234096/234096 - 154s - loss: 0.1544 - recall: 0.9982 - precision: 0.9619\n",
      "Epoch 2/5\n",
      "234096/234096 - 156s - loss: 0.1493 - recall: 0.9989 - precision: 0.9627\n",
      "Epoch 3/5\n",
      "234096/234096 - 147s - loss: 0.1492 - recall: 0.9988 - precision: 0.9628\n",
      "Epoch 4/5\n",
      "234096/234096 - 161s - loss: 0.1489 - recall: 0.9987 - precision: 0.9630\n",
      "Epoch 5/5\n",
      "234096/234096 - 177s - loss: 0.1482 - recall: 0.9987 - precision: 0.9636\n",
      "26011/26011 - 16s - loss: 0.1490 - recall: 0.9988 - precision: 0.9675\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "234096/234096 - 177s - loss: 0.0493 - recall: 0.9955 - precision: 0.9805\n",
      "Epoch 2/5\n",
      "234096/234096 - 168s - loss: 0.0273 - recall: 0.9891 - precision: 0.9954\n",
      "Epoch 3/5\n",
      "234096/234096 - 150s - loss: 0.0270 - recall: 0.9880 - precision: 0.9965\n",
      "Epoch 4/5\n",
      "234096/234096 - 156s - loss: 0.0272 - recall: 0.9879 - precision: 0.9968\n",
      "Epoch 5/5\n",
      "234096/234096 - 162s - loss: 0.0273 - recall: 0.9876 - precision: 0.9973\n",
      "26011/26011 - 15s - loss: 0.0261 - recall: 0.9996 - precision: 0.9847\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "234096/234096 - 174s - loss: 0.0425 - recall: 0.9982 - precision: 0.9843\n",
      "Epoch 2/5\n",
      "234096/234096 - 126s - loss: 0.0219 - recall: 0.9985 - precision: 0.9929\n",
      "Epoch 3/5\n",
      "234096/234096 - 118s - loss: 0.0217 - recall: 0.9985 - precision: 0.9929\n",
      "Epoch 4/5\n",
      "234096/234096 - 118s - loss: 0.0217 - recall: 0.9985 - precision: 0.9930\n",
      "Epoch 5/5\n",
      "234096/234096 - 117s - loss: 0.0217 - recall: 0.9986 - precision: 0.9930\n",
      "26011/26011 - 11s - loss: 0.0176 - recall: 0.9995 - precision: 0.9930\n",
      "Epoch 1/5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 90, in __call__\n",
      "    score = scorer(estimator, *args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/sklearn/metrics/_scorer.py\", line 397, in _passthrough_scorer\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/amine/.local/lib/python3.9/site-packages/keras/wrappers/scikit_learn.py\", line 305, in score\n",
      "    raise ValueError('The model is not configured to compute accuracy. '\n",
      "ValueError: The model is not configured to compute accuracy. You should pass `metrics=[\"accuracy\"]` to the `model.compile()` method.\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "234096/234096 - 118s - loss: 0.0910 - recall: 0.9889 - precision: 0.9747\n",
      "Epoch 2/5\n",
      "234096/234096 - 115s - loss: 0.0860 - recall: 0.9881 - precision: 0.9765\n",
      "Epoch 3/5\n",
      "234096/234096 - 107s - loss: 0.0857 - recall: 0.9881 - precision: 0.9764\n",
      "Epoch 4/5\n"
     ]
    }
   ],
   "source": [
    "attacks = [\"Mirai\", \"RouterSploit\", \"UFOnet\"]\n",
    "\n",
    "\n",
    "\n",
    "for attack in attacks:\n",
    "    print(attack)\n",
    "    dataset_folder = \"/home/amine/Documents/CRIM_Project/energy/\"+attack+\"/\"\n",
    "    input_folder = dataset_folder+\"pre_ml-\"+attack+\".csv\"\n",
    "    dataframe = pd.read_csv(input_folder, delimiter=',')\n",
    "    # load dataset\n",
    "    dataset = dataframe.values\n",
    "    # split into input (X) and output (Y) variables\n",
    "    X = dataset[:,0:6].astype(float)\n",
    "    Y = dataset[:,6]\n",
    "\n",
    "\n",
    "    # encode class values as integers\n",
    "    encoder = LabelEncoder()\n",
    "    encoder.fit(Y)\n",
    "    encoded_Y = encoder.transform(Y)\n",
    "\n",
    "\n",
    "    # baseline model\n",
    "    def create_baseline():\n",
    "        # create model\n",
    "        model = Sequential()\n",
    "        model.add(Dense(6, input_dim=6, activation='relu'))\n",
    "        model.add(Dense(1, activation='sigmoid'))\n",
    "        # Compile model\n",
    "        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['Recall', \"Precision\"])\n",
    "        return model\n",
    "\n",
    "\n",
    "\n",
    "    # evaluate model with standardized dataset\n",
    "    estimator = KerasClassifier(build_fn=create_baseline, epochs=5, batch_size=1, verbose=2)\n",
    "    kfold = StratifiedKFold(n_splits=10, shuffle=True)\n",
    "    results = cross_val_score(estimator, X, encoded_Y, cv=kfold)\n",
    "    print(\"Baseline: %.2f%% (%.2f%%)\" % (results.mean()*100, results.std()*100))\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f60e9037",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
